/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/notes/Docker': RouteRecordInfo<'/notes/Docker', '/notes/Docker', Record<never, never>, Record<never, never>>,
    '/notes/Git': RouteRecordInfo<'/notes/Git', '/notes/Git', Record<never, never>, Record<never, never>>,
    '/notes/Linux': RouteRecordInfo<'/notes/Linux', '/notes/Linux', Record<never, never>, Record<never, never>>,
    '/notes/Pm2': RouteRecordInfo<'/notes/Pm2', '/notes/Pm2', Record<never, never>, Record<never, never>>,
    '/notes/Tmux': RouteRecordInfo<'/notes/Tmux', '/notes/Tmux', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/Defeating_Nondeterminism': RouteRecordInfo<'/posts/Defeating_Nondeterminism', '/posts/Defeating_Nondeterminism', Record<never, never>, Record<never, never>>,
    '/posts/Defi_Mooc': RouteRecordInfo<'/posts/Defi_Mooc', '/posts/Defi_Mooc', Record<never, never>, Record<never, never>>,
    '/posts/Deterministic_SGLang': RouteRecordInfo<'/posts/Deterministic_SGLang', '/posts/Deterministic_SGLang', Record<never, never>, Record<never, never>>,
    '/posts/GPU_TEE': RouteRecordInfo<'/posts/GPU_TEE', '/posts/GPU_TEE', Record<never, never>, Record<never, never>>,
    '/posts/LLM_Inference_Frameworks': RouteRecordInfo<'/posts/LLM_Inference_Frameworks', '/posts/LLM_Inference_Frameworks', Record<never, never>, Record<never, never>>,
    '/posts/WASM': RouteRecordInfo<'/posts/WASM', '/posts/WASM', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes: '/'
      views: never
    }
    'pages/[...404].md': {
      routes: '/[...404]'
      views: never
    }
    'pages/notes/index.md': {
      routes: '/notes/'
      views: never
    }
    'pages/notes/Docker.md': {
      routes: '/notes/Docker'
      views: never
    }
    'pages/notes/Git.md': {
      routes: '/notes/Git'
      views: never
    }
    'pages/notes/Linux.md': {
      routes: '/notes/Linux'
      views: never
    }
    'pages/notes/Pm2.md': {
      routes: '/notes/Pm2'
      views: never
    }
    'pages/notes/Tmux.md': {
      routes: '/notes/Tmux'
      views: never
    }
    'pages/posts/index.md': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/Defeating_Nondeterminism.md': {
      routes: '/posts/Defeating_Nondeterminism'
      views: never
    }
    'pages/posts/Defi_Mooc.md': {
      routes: '/posts/Defi_Mooc'
      views: never
    }
    'pages/posts/Deterministic_SGLang.md': {
      routes: '/posts/Deterministic_SGLang'
      views: never
    }
    'pages/posts/GPU_TEE.md': {
      routes: '/posts/GPU_TEE'
      views: never
    }
    'pages/posts/LLM_Inference_Frameworks.md': {
      routes: '/posts/LLM_Inference_Frameworks'
      views: never
    }
    'pages/posts/WASM.md': {
      routes: '/posts/WASM'
      views: never
    }
    'pages/projects.md': {
      routes: '/projects'
      views: never
    }
    'pages/streams.md': {
      routes: '/streams'
      views: never
    }
    'pages/use.md': {
      routes: '/use'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
