/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bar': RouteRecordInfo<'/bar', '/bar', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/chat-zh': RouteRecordInfo<'/chat-zh', '/chat-zh', Record<never, never>, Record<never, never>>,
    '/collective-sponsor-onetime': RouteRecordInfo<'/collective-sponsor-onetime', '/collective-sponsor-onetime', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/podcasts': RouteRecordInfo<'/podcasts', '/podcasts', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/about-yak-shaving': RouteRecordInfo<'/posts/about-yak-shaving', '/posts/about-yak-shaving', Record<never, never>, Record<never, never>>,
    '/posts/about-yak-shaving-zh': RouteRecordInfo<'/posts/about-yak-shaving-zh', '/posts/about-yak-shaving-zh', Record<never, never>, Record<never, never>>,
    '/posts/domain-email': RouteRecordInfo<'/posts/domain-email', '/posts/domain-email', Record<never, never>, Record<never, never>>,
    '/posts/get-package-root': RouteRecordInfo<'/posts/get-package-root', '/posts/get-package-root', Record<never, never>, Record<never, never>>,
    '/posts/github-alerts': RouteRecordInfo<'/posts/github-alerts', '/posts/github-alerts', Record<never, never>, Record<never, never>>,
    '/posts/github-co-authors': RouteRecordInfo<'/posts/github-co-authors', '/posts/github-co-authors', Record<never, never>, Record<never, never>>,
    '/posts/hello-tokyo': RouteRecordInfo<'/posts/hello-tokyo', '/posts/hello-tokyo', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes: '/'
      views: never
    }
    'pages/[...404].md': {
      routes: '/[...404]'
      views: never
    }
    'pages/bar.md': {
      routes: '/bar'
      views: never
    }
    'pages/bookmarks.md': {
      routes: '/bookmarks'
      views: never
    }
    'pages/chat.md': {
      routes: '/chat'
      views: never
    }
    'pages/chat-zh.md': {
      routes: '/chat-zh'
      views: never
    }
    'pages/collective-sponsor-onetime.md': {
      routes: '/collective-sponsor-onetime'
      views: never
    }
    'pages/demos.md': {
      routes: '/demos'
      views: never
    }
    'pages/media.md': {
      routes: '/media'
      views: never
    }
    'pages/notes.md': {
      routes: '/notes'
      views: never
    }
    'pages/photos.md': {
      routes: '/photos'
      views: never
    }
    'pages/podcasts.md': {
      routes: '/podcasts'
      views: never
    }
    'pages/posts/index.md': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/about-yak-shaving.md': {
      routes: '/posts/about-yak-shaving'
      views: never
    }
    'pages/posts/about-yak-shaving-zh.md': {
      routes: '/posts/about-yak-shaving-zh'
      views: never
    }
    'pages/posts/domain-email.md': {
      routes: '/posts/domain-email'
      views: never
    }
    'pages/posts/get-package-root.md': {
      routes: '/posts/get-package-root'
      views: never
    }
    'pages/posts/github-alerts.md': {
      routes: '/posts/github-alerts'
      views: never
    }
    'pages/posts/github-co-authors.md': {
      routes: '/posts/github-co-authors'
      views: never
    }
    'pages/posts/hello-tokyo.md': {
      routes: '/posts/hello-tokyo'
      views: never
    }
    'pages/projects.md': {
      routes: '/projects'
      views: never
    }
    'pages/sponsors-list.md': {
      routes: '/sponsors-list'
      views: never
    }
    'pages/streams.md': {
      routes: '/streams'
      views: never
    }
    'pages/use.md': {
      routes: '/use'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
